platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'LTMSwift_Example' do
  pod 'LTMSwift', :path => '../'

  target 'LTMSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
