platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'LTMSwift_Example' do
  pod 'LTMSwift', :path => '../'

  target 'LTMSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
